### DISCUSSION TITLE
Connection to and operations against Redis cluster take too long and timeout

### DISCUSSION THREAD

**Discussion by giuseppe-sirigu** [Grokzen/redis-py-cluster#490] [Q&A] [answered]
I have been trying to connect to a local Redis cluster built with the following docker-compose:

```yml
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    restart: always
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    ports:
      - "7000:6379"

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    restart: always
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    ports:
      - "7001:6379"

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    restart: always
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    ports:
      - "7002:6379"

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2
    restart: always
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    ports:
      - "7003:6379"

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2
    restart: always
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    ports:
      - "7004:6379"

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.2
    restart: always
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    ports:
      - "7005:6379"

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
```

Then I installed `redis-py-cluster==2.1.3` on my Python 3.9 environment and tried to run the following script:
```python
import rediscluster
startup_nodes = [{"host": "127.0.0.1", "port": "7000"},
                             {"host": "127.0.0.1", "port": "7001"},
                             {"host": "127.0.0.1", "port": "7002"},
                             {"host": "127.0.0.1", "port": "7003"},
                             {"host": "127.0.0.1", "port": "7004"},
                             {"host": "127.0.0.1", "port": "7005"}]
client = rediscluster.RedisCluster(
    startup_nodes=startup_nodes,
    decode_responses=True,
    password=self.redis_psswd,
    skip_full_coverage_check=False
)
ping = client.ping()
```

But the commands timeout and I get the following error: `Error 10060 connecting to 192.168.32.4:6379. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected`

Why is this happening?
